"""A class to compute the band specific energy for each participant.

Created on: April 2025
Author: Udesh Habaraduwa

Attributes
----------
channel_names (list[str]): Standard list of 26 EEG channel names.
n_eeg_channels (int): Number of EEG channels (fixed at 26).
all_freq_bands (dict): Dictionary mapping frequency band names (e.g., 'delta') 
                       to tuples containing frequency range ([min_hz, max_hz]) 
                       and a canonical band index.
cleaned_path (str): Path to the directory containing preprocessed EEG data files.
select_freq_bands (list[str]): List of frequency band names to compute energy for,
                               ordered canonically (delta, theta, alpha, beta, gamma).
include_bad_channels_psd (bool): Whether to include channels marked as bad during 
                                   PSD computation. Defaults to True.
ran_energy (bool): Flag indicating if `run_energy_parallel` has been executed. 
                   Initialized to False.
save_to_disk (bool): Whether to save computed energy matrices to disk. 
                     Defaults to True.
energy_plots (bool): Whether to generate and save plots of the energy matrices. 
                     Defaults to False.
full_time_series (bool): Whether to compute energy on the full time series 
                           instead of epochs. Defaults to False.
method_psd (str): Method used for PSD computation by the underlying 
                  `PowerSpectrum` class. Defaults to 'welch'.
fmin_psd (float): Minimum frequency for PSD computation. Defaults to 0.5.
fmax_psd (float): Maximum frequency for PSD computation. Defaults to 130.
tmax_psd (float | None): Maximum time for PSD computation. Defaults to None.
picks_psd (list[str] | None): Channels selected for PSD computation. 
                                Defaults to None (uses MNE default).
proj_psd (bool): Whether projection was applied during PSD computation. 
                     Defaults to False.
verbose_psd (bool): Verbosity setting for the underlying PSD computation. 
                        Defaults to False.
participant_list (list[str]): List of participant identifiers found in 
                                  `cleaned_path`.
labels_dict (dict): Dictionary mapping participant IDs to their labels.
project_root (Path): The root directory of the project.
plot_save_dir (Path): Directory path for saving energy plots.
energy_save_dir (Path): Directory path for saving full time series energy matrices.
energy_save_dir_epoched (Path): Directory path for saving epoched energy matrices.
folders_and_files (list[tuple[Path, str]]): List of (folder_path, file_name) 
                                            tuples for processing.
participant_npy_files (list[str]): List of .npy file names to be processed.
testing (bool): Flag indicating if the class is used in a testing context. 
                Defaults to False.

Methods
-------
__init__:
    Initialize the Energy class.
__len__:
    Return the number of participants in the dataset.
__getitem__:
    Return the energy for a given participant.
get_energy:
    Compute the energy for a given participant.
run_energy_parallel:
    Compute the energy for all participants in parallel.    

"""

import math
import multiprocessing
import os
import random
import time
from itertools import permutations
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import Dataset
from tqdm import tqdm

from eeglearn.config import Config
from eeglearn.features.spectrum import PowerSpectrum
from eeglearn.utils.utils import (
    get_cleaned_data_paths,
    get_labels_dict,
    get_participant_id_condition_from_string,
    hamming_set,
)


def worker_init_fn(worker_id : int, seed : int = None) -> None:
    """Initialize random seed for multiprocessing workers.

    Given the seed management system implemented globally, this function is used
    in the parallel processing of permutations to give a different sequence
    to each process. Otherwise, each process applies and returns the same pseudolabel

    THIS FUNCTION WAS GENERATED BY AI.
    INSPECTEED AND VERIFIED BY AUTHOR.
    """
    if not(seed):
        seed = os.getpid() + int(time.time() * 1000)
        random.seed(seed)
        np.random.seed(seed % (2**32 - 1)) # Numpy seed must be between 0 and 2**32 - 1
        # If using torch.rand or similar in workers, seed it too:
        torch.manual_seed(seed) 
        torch.cuda.manual_seed_all(seed) # If using GPU
    else:
        Config.set_global_seed()


class Energy(Dataset):
    """A class to compute the band specific energy for each participant.

    Methods
    -------
    __init__:
        Initialize the Energy class.
    __len__:
        Return the number of participants in the dataset.
    __getitem__:
        Return the energy for a given participant.
    get_energy:
        Compute the energy for a given participant.
    run_energy_parallel:
        Compute the energy for all participants in parallel.    

    """

    def __init__(self, 
                 cleaned_path : str,
                 select_freq_bands : list[str] = None,
                 save_to_disk : bool = True,
                 energy_plots : bool = False,
                 full_time_series : bool = False,
                 method_psd : str = 'welch',
                 fmin_psd : float = 0.5,
                 fmax_psd : float = 130,
                 tmax_psd : float  = None,
                 picks_psd : list[str] = None,
                 include_bad_channels_psd : bool = True,
                 proj_psd : bool = False, 
                 verbose_psd : bool = False,
                 ) -> None:
        """Dataset class for computing and loading energy features from EEG data.

        δ (1-3 Hz)
        θ (4-7 Hz)
        α (8-13 Hz)
        β (14-30 Hz)
        γ (31-50 Hz)

        Args:
        ----
            cleaned_path (str): Path to the cleaned data.
            select_freq_bands (list[str]): List of frequency bands.
            save_to_disk (bool): Whether to save the energy to disk.
            get_labels (bool): Whether to get the labels.
            plots (bool): Whether to plot the energy.
            verbose (bool): Whether to print verbose output.
            full_time_series (bool): Whether to use the full time series.
            method_psd (str): Method to use for PSD computation.
            fmin_psd (float): Minimum frequency for PSD computation.
            fmax_psd (float): Maximum frequency for PSD computation.
            tmax_psd (float): Maximum time for PSD computation.
            picks_psd (list[str]): List of channels to compute the energy for.
            energy_plots (bool): Whether to plot the energy.
            proj_psd (bool): Whether to project the PSD.
            verbose_psd (bool): Whether to print verbose output.
            include_bad_channels_psd (bool): Whether to include bad
              channels in the PSD computation.

        """
        self.channel_names: list[str] =  ['Fp1', 'Fp2', 'F7', 
                               'F3', 'Fz', 'F4', 
                               'F8', 'FC3', 'FCz', 
                               'FC4', 'T7', 'C3', 'Cz', 'C4', 'T8', 
                               'CP3', 'CPz', 'CP4', 'P7', 'P3', 'Pz', 
                               'P4', 'P8', 'O1', 'Oz', 'O2']
        self.n_eeg_channels = 26
        # Define all available frequency bands, and the index of the band
        self.all_freq_bands :dict[tuple[list,int]] = {
            'delta': ([1, 3], 0),
            'theta': ([4, 7], 1),
            'alpha': ([8, 13], 2),
            'beta': ([14, 30], 3),
            'gamma': ([31, 50], 4)
        }
        self.cleaned_path : str = cleaned_path
        assert os.path.exists(self.cleaned_path), "cleaned_path does not exist"
        if select_freq_bands is None:
            # this is guaranteed to be in inserstion order
            select_freq_bands : list[str] = list(self.all_freq_bands.keys())
            self.select_freq_bands = select_freq_bands
        else:
            assert isinstance(select_freq_bands, list), \
                "select_freq_bands must be a list"
            assert all(band in self.all_freq_bands for band in select_freq_bands), \
                "Invalid frequency band."
            self.select_freq_bands = select_freq_bands
        
        assert len(self.select_freq_bands) == len(select_freq_bands),\
            "Requested bands and reorderd bands differ in length"
        self.include_bad_channels_psd : bool = include_bad_channels_psd
        if include_bad_channels_psd:
            assert isinstance(include_bad_channels_psd, bool),\
                "include_bad_channels_psd must be a bool"
            self.include_bad_channels_psd : bool = include_bad_channels_psd
        self.ran_energy : bool = False  
        self.save_to_disk : bool = save_to_disk
        self.energy_plots : bool = energy_plots
        self.full_time_series : bool = full_time_series
        self.method_psd : str = method_psd
        self.fmin_psd : float = fmin_psd
        self.fmax_psd : float = fmax_psd
        self.tmax_psd : float = tmax_psd
        self.picks_psd : list[str] = picks_psd
        self.proj_psd : bool = proj_psd
        self.participant_list : list[str] = os.listdir(self.cleaned_path)
        assert len(self.participant_list) > 0, "No participants found in cleaned_path"
        self.labels_dict : dict = get_labels_dict()
        assert self.labels_dict is not None, "labels_dict is None"
        self.verbose_psd : bool = verbose_psd

        self.project_root : Path = Path(__file__).resolve().parent.parent.parent
        assert self.project_root.name == \
            'eeg-graph-learning',"project_root is not eeg-graph-learning"
        
        self.plot_save_dir : Path = self.project_root / 'data' / 'energy' / 'plots'
        self.plot_save_dir.mkdir(parents=True, exist_ok=True)
        assert os.path.exists(self.plot_save_dir), "Plotting directory path invalid"
        self.energy_save_dir : Path = self.project_root / 'data' / 'energy' /\
              "energy_full"
        self.energy_save_dir.mkdir(parents=True, exist_ok=True)
        assert os.path.exists(self.energy_save_dir),\
            " Energy save directory path invalid"
        self.energy_save_dir_epoched : Path = self.project_root \
            / 'data' / 'energy' / 'energy_epoched'
        self.energy_save_dir_epoched.mkdir(parents=True, exist_ok=True)
        assert os.path.exists(self.energy_save_dir_epoched), \
            "Energy epoched directory path invalid"
        
        self.save_freq_perms_to_disk : bool = False
        self.save_spatial_perms_to_disk : bool  = False
        
        
        # Get the actual number of numpy files to process
        self.folders_and_files : list[tuple[Path, str]] = [] 
        self.participant_npy_files : list[str] = []
        self.folders_and_files, self.participant_npy_files = \
            get_cleaned_data_paths(self.participant_list, self.cleaned_path) 
        
        # permutations for band shuffling
        self.possible_perms : dict[int, tuple[str, ...]] =\
            dict(enumerate(permutations(self.select_freq_bands)))


        assert len(self.participant_npy_files) > 0,"No .npy files found in cleaned_path"

    def __len__(self):
        """Return the number of EEG data files in the dataset.
        
        Returns
        -------
            int: The number of .npy files across all participant folders.

        """
        return len(self.participant_npy_files)

    def __getitem__(self, idx : int) -> tuple[torch.Tensor, torch.Tensor, str]:
        """Get band energy data for a specific file based on index.
        
        This method computes the band energy data if it hasn't been computed already,
        then returns the data for the file at the specified index.
        
        Args:
        ----
            idx (int): Index of the file in the participant_npy_files list.
            
        Returns:
        -------
            tuple: Contains:
                - torch.Tensor: The band energy data.
                - str: The participant label (if get_labels is True).
                
        Note:
        ----
            If the spectrum file is not found, returns (None, None, None).

        """
        # make sure the spectrum is computed first
        assert self.save_to_disk,\
    "Designed to index by loading. Instantiate energy object with save_to_disk= True"
        if not self.ran_energy:
            self.run_energy_parallel()
        try:
            participant_id, condition =  get_participant_id_condition_from_string\
                (self.participant_npy_files[idx])
            label = self.labels_dict[participant_id]
            if self.full_time_series:
                energy = torch.load(self.energy_save_dir /\
                                      f'energy_{participant_id}_{condition}.pt')
            else:
                energy = torch.load(self.energy_save_dir_epoched /\
                                      f'energy_{participant_id}_{condition}.pt')
            return energy, label
        except IndexError:
            print(f'Energy for {self.participant_npy_files[idx]} not found')
            return None, None, None
        except FileNotFoundError:
            print(f'Energy for {self.participant_npy_files[idx]} not found')
            return None, None, None
    
    def plot_energy(self,):
        """Plot the energy of the EEG data for a given participant."""
        pass

    def get_energy(self, folder_path:  Path, file_name: str) -> tuple[torch.Tensor,
                                                                      list[str]]:
        """Compute the energy of the EEG data for one file.

        Args:
        ----
            folder_path (Path): The path to the folder containing the EEG data.
            file_name (str): The name of the file containing the EEG data.

        Returns:
        -------
            tuple: Contains:
                - torch.Tensor: The energy of the EEG data, with shape:
                  - For full_time_series=True: (n_channels, n_bands)
                  - For full_time_series=False: (n_epochs, n_channels, n_bands)
                - list[str]: Channel names corresponding to the rows in the energ
                             matrix.

        Notes:
        -----
            - For full time series, computes energy across all frequency bands and 
                returns a matrix of shape (n_channels, n_bands).
            - For epoched data, computes energy for each epoch and returns a tensor of
              shape (n_epochs, n_channels, n_bands).
            - If save_to_disk is True, saves the energy data to disk in the appropriate
              directory (energy_save_dir or energy_save_dir_epoched).

        """
        participant_id : str
        condition : str
        participant_id, condition = get_participant_id_condition_from_string(file_name)
        path_to_file : Path = folder_path / file_name
        assert os.path.exists(path_to_file),f"file does not exist: {path_to_file}"

        #get the spectrum
        spectra : torch.Tensor
        freqs : torch.Tensor
        n_bad_channels : int 
        n_channels_included : int
        spectrum : PowerSpectrum = PowerSpectrum(
                                                cleaned_path=self.cleaned_path,
                                                full_time_series=self.full_time_series,
                                                fmin= \
                                                    self.all_freq_bands['delta'][0][0],
                                                fmax= \
                                                    self.all_freq_bands['gamma'][0][1],
                                                verbose=self.verbose_psd,
                                                picks=self.picks_psd,
                                                include_bad_channels= \
                                                    self.include_bad_channels_psd,
                                                save_to_disk=False)
        spectra, freqs, _, n_bad_channels, ch_names = spectrum.get_spectrum(
            folder_path=folder_path,
            file_name=file_name,
            save_to_disk=False)
        n_epochs = spectra.shape[0]
        assert not torch.isnan(spectra).any(), "spectra contains nans"
        assert not torch.isnan(freqs).any(), "freqs contains nans"
        n_freqs : int = len(freqs)
        masks : dict = {
            "delta" : (freqs >= 1) & (freqs <= 3),
            "theta" : (freqs >= 4) & (freqs <= 7),
            "alpha" : (freqs >= 8) & (freqs <= 13),
            "beta" :  (freqs >= 14) & (freqs <= 30),
            "gamma" : (freqs >= 31) & (freqs <= 50)
        }
        if self.full_time_series:
            # if include_bads --> do not subtract
            # if (not include_bads) --> subtract 
            n_channels_included = self.n_eeg_channels - \
                (1 - self.include_bad_channels_psd)*(n_bad_channels)
            assert spectra.shape[1] == n_freqs, \
                "spectra and freqs have different number of frequencies"
            band_energies : dict = {
                "delta" : torch.sum(spectra[:,masks['delta']], dim = 1),
                "theta" : torch.sum(spectra[:,masks['theta']], dim = 1),
                "alpha" : torch.sum(spectra[:,masks['alpha']], dim = 1),
                "beta"  : torch.sum(spectra[:,masks['beta']], dim = 1),
                "gamma" : torch.sum(spectra[:,masks['gamma']], dim = 1)
            }
            assert band_energies['delta'].shape == \
            band_energies['theta'].shape == \
                band_energies['alpha'].shape == \
                band_energies['beta'].shape == \
                band_energies['gamma'].shape ==  (n_channels_included,), \
                    "Band energies have different shapes"
            # combine the band energies into a single tensor
            # n_channels x n_bands
            selected_bands : list = [band_energies[band] for \
                                      band in self.select_freq_bands]
            combined_energy : torch.Tensor = torch.cat(selected_bands).\
                reshape(n_channels_included,-1)
            assert combined_energy.shape == (n_channels_included, 
                                             len(self.select_freq_bands)), \
                "combined_energy has wrong shape"
            if self.save_to_disk:
                torch.save((combined_energy,ch_names), self.energy_save_dir /\
                            f"energy_{participant_id}_{condition}.pt")
            return (combined_energy.float(),ch_names)
        else:
            n_channels_included = self.n_eeg_channels - \
                (1 - self.include_bad_channels_psd)*(n_bad_channels)
            assert spectra.shape[2] == n_freqs,\
                "spectra and freqs have different number of frequencies"
            # There are 5 matrices of shape (n_epochs x n_channels x n_freq_bins)
            # we collapse the frequency bins dimension by summing it up
            # to get a matrix of (n_epochs x n_channels) for each band      
            band_energies : dict = {
                "delta" : torch.sum(spectra[:,:,masks['delta']], dim = 2),
                "theta" : torch.sum(spectra[:,:,masks['theta']], dim = 2),
                "alpha" : torch.sum(spectra[:,:,masks['alpha']], dim = 2),
                "beta"  : torch.sum(spectra[:,:,masks['beta']], dim = 2),
                "gamma" : torch.sum(spectra[:,:,masks['gamma']], dim = 2)
            }
            #print("band energy : ", band_energies["delta"].shape)
            assert band_energies['delta'].shape == \
            band_energies['theta'].shape == \
                band_energies['alpha'].shape == \
                band_energies['beta'].shape == \
                band_energies['gamma'].shape ==  (n_epochs, n_channels_included), \
                    "Band energies have different shapes"
            
            # a list of len(n_select_freq_bands) n_epochs x n_channels tensors
            selected_bands : list = [band_energies[band] for \
                                      band in self.select_freq_bands]
            # (n_epochs x n_channel x n_bands)
            combined_energy : torch.Tensor = torch.stack(selected_bands,
                                                          dim = 1).permute(0,2,1)
       
            first_band : str = self.select_freq_bands[0] 
            # check that the energy for a given band in a given epoch is where it 
            # should be
            assert torch.allclose(combined_energy[0,:,0],
                                  band_energies[first_band][0,:])
            expected_shape : tuple = (n_epochs,
                                      n_channels_included,len(self.select_freq_bands))
            assert combined_energy.shape ==\
                (n_epochs,n_channels_included, len(self.select_freq_bands)),\
            f"{combined_energy.shape} != ({expected_shape})"

            if self.save_to_disk:
                torch.save((combined_energy, ch_names), self.energy_save_dir_epoched /\
                            f"energy_{participant_id}_{condition}.pt")
            #print(f"print {combined_energy.shape}")
            return (combined_energy.float(),ch_names)
        

    def run_energy_parallel(self) -> None | list:
        """ 
        Compute band energy for all participants and conditions in parallel.
        
        It uses the get_energy method for individual
        file processing and uses a process pool to distribute the workload.
        
        The method sets ran_energy to True to indicate that energy computation has 
        been performed, to make sure when called by __getitem__ it does not compute
        the energy again.

        Args:
        ----
            None

        Returns:
        -------
            None : if saved to disk
            list : List of energy matrices

        """
        self.ran_energy = True
        processes = multiprocessing.cpu_count() - 1
        max_processes = multiprocessing.cpu_count() -1
        processes = len(self.folders_and_files) if len(self.folders_and_files) < \
                                            max_processes else max_processes
        print(f'Using {processes} processes for energy computation')
        with multiprocessing.Pool(processes) as p:
            results : list[torch.Tensor] = \
                list(tqdm(p.starmap(self.get_energy, self.folders_and_files), 
                     total=len(self.folders_and_files), 
                     desc="Computing Energy bands"))
            if not self.save_to_disk:
                return results
            
    def get_freq_permutation(self, data : torch.Tensor = None,
                         file_name : str = None) -> tuple[torch.Tensor,int]:
        """Get all the frequency band permutations of the data.
        
        Takes a (n_epochs x n_channels x n_bands) or (n_channels x n_bands ) energy
        matrix and generates a permutation of the bands. 

        Args:
        ----
            data (torch.Tensor): A (optionally n_epochs) x n_channels x n_bands tensor.
            file_name : File name containing participant id and condition ending in
                        .pt.
            save_to_disk : if permutations should be saved to disk, default false
            is_epoched : If the incoming data is epoched.

        Returns:
        -------
            tuple: Contains:
                - torch.Tensor: The permuted data.
                - np.array : The pseudolabels representing which permutation was 
                            applied.
                - file_name : file name of the participant.

        """
        if data is None:
            if os.path.exists(self.energy_save_dir_epoched / file_name):
                data = torch.load(self.energy_save_dir_epoched / file_name)[0]
            else:
                data = torch.load(self.energy_save_dir / file_name)[0]
        assert isinstance(data, torch.Tensor)
        # Assert shape for non-epoched and epoched cases
        assert len(data.shape) ==2 or len(data.shape) == 3
        #is_epoched = True if len(data.shape)==3 else False

        if len(data.shape) == 2:
            # reshape to a 3-d matrix with 1 epochs dimension
            data = data.reshape(-1,*data.shape)
        n_epochs = data.shape[0]
        #print(f"data shape : {data.shape}")
        band_position : dict = {band : i for i, band \
                                in enumerate(self.select_freq_bands)}

        # pseudolabels, one per epoch.
        pseudo_labels : np.array = np.random.randint(0,
                                        math.factorial(len(self.select_freq_bands))\
                                            , size = n_epochs)
        
        permutations_per_epoch : list[int] = [self.possible_perms[pseudo_label]
                                            for pseudo_label in pseudo_labels]
        
        shuffled_band_indices: list[list[int]] = [
                                    [band_position[band] for band in permutation]
                                        for permutation in permutations_per_epoch]
        
        try:
            shuffled_columns : torch.Tensor = torch.zeros(data.shape)
            for epoch_num, shuffled_bands in enumerate(shuffled_band_indices):
                shuffled_columns[epoch_num,:,:] = data[epoch_num,:,shuffled_bands]

        except IndexError as err:
            raise IndexError("A mismatch between expected bands. "
                                "Usually a result of having run test_energy.py. "
                                "Delete the energy folder in data and retry.") from \
                                err
        assert shuffled_columns.shape == data.shape
        assert shuffled_columns.shape == data.shape,\
                "Input and shuffled data should match"
        assert shuffled_columns.shape[0] == len(pseudo_labels),\
                "Should be as many pseudolabels as there are epochs"
        if self.save_freq_perms_to_disk:
            self.perm_save_dir : Path = self.project_root /\
                'data' / 'energy' / 'frequency_perms'
            self.perm_save_dir.mkdir(parents=True, exist_ok=True)
            assert os.path.exists(self.perm_save_dir),\
                "Permutation save directory path invalid"
            
            save_path = self.perm_save_dir / f"energy_perms_{file_name}"
            torch.save((shuffled_columns, pseudo_labels, file_name), save_path)
            assert os.path.exists(save_path),\
                f"Data file does not exist: {save_path}"
        return (shuffled_columns.float(),pseudo_labels, file_name) 
    
    def run_freq_permutations_parallel(self, save_to_disk : bool = False,
                                        seed : int = None)-> None | list:
        """Compute band energy permutations for all files in parallel.

        Uses unique random seeds for each worker.
        It uses the get_permutaion method for individual
        file processing and uses a process pool to distribute the workload.

        Args:
        ----
            save_to_disk (bool): Whether to save the permutations to disk.
            seed (int, optional): Seed value for reproducible permutations.
                If None, uses system-based random seed.

        Returns:
        -------
            list : List of permutations for each energy matrix

        NOTE: Problem with sending multiple arguments to starmap solved with AI

        """
        starmap_args = []
        max_processes = multiprocessing.cpu_count() -1

        if save_to_disk:
            self.save_freq_perms_to_disk = True
        # Files from energy_save_dir are NOT epoched
        full_length_energy_files = os.listdir(self.energy_save_dir)
        print("full len :",len(full_length_energy_files))
        for filename in full_length_energy_files:
            starmap_args.append((None,filename))

        # Files from energy_save_dir_epoched ARE epoched
        epoched_energy_files = os.listdir(self.energy_save_dir_epoched)
        for filename in epoched_energy_files:
            starmap_args.append((None,filename))
            
        print("epoched :",len(epoched_energy_files))

        processes = len(starmap_args) if len(starmap_args) < max_processes \
                                                                else max_processes
        
        print(f'Using {processes} processes for frequency permutation computation')
        print(f"Processing {len(starmap_args)} files...")

        # This is the same except does not use the correction for starting
        # each new process with a different seed. It is used for testing.
        with multiprocessing.Pool(processes, initializer=worker_init_fn,
                                    initargs=(os.getpid(),seed)) \
            as p:
            results = list(tqdm(p.starmap(self.get_freq_permutation, starmap_args),
                                total=len(starmap_args),
                                desc="Computing frequency band permutations"))

        print(f"Finished processing {len(results)} permutations.")

        return results
    
    def get_spatial_permutation(self,
                                file_name : str = None,
                                ch_names : list[str] = None,
                                data : torch.Tensor = None,
                                hamming_selection: str = "max")\
                                    -> tuple[torch.Tensor, int]:
        """Shuffle the regions of an energy matrix.
        
        Args:
        ----
            data : An energy band matrix of shape n_epochs x n_channels x n_bands
                   or n_channels x n_bands for a full time series.
                   If none, it will be loaded from disk.
            file_name : The file name of the energy object to load if data is not
                        provided.
            ch_names : A list of channel names where the index of each entry 
                       coressponds to that channels row index in the data matrix
            hamming_selection :  Choose the maximally different permutation ("max") 
                                to be included at iteration or the median ("median"). 

        Returns:
        -------
            tuple[torch.Tensor : A matrix permuted by regions.
                  np.array : a n_epochs length vector  of pseudo labels
                               indicating the permutation applied to each epoch.
                 file_name : participant identifier ] 
                
        
        """
        # synchronize seed for testing permutation generation between parallel
        # serial processing testing.
        n_regions : int = 10
        n_permutations : int = 128
        if data is None:
            assert file_name is not None,\
                "If data is not provided, requires a file name to load from disk"
            if os.path.exists(self.energy_save_dir_epoched / file_name):
                data, ch_names = torch.load(self.energy_save_dir_epoched / file_name)
            else:
                data,ch_names = torch.load(self.energy_save_dir / file_name)
            
        assert isinstance(data, torch.Tensor)
        # Assert shape for non-epoched and epoched cases
        assert len(data.shape) >=2 or len(data.shape) <= 3

        assert isinstance(data, torch.Tensor), "Input should be a torch.Tensor object."
        assert isinstance(ch_names, list), "Input should be a list of strings."
        # for non-epoched objects
        if len(data.shape) == 2:
            assert data.shape[0] == len(ch_names), \
            "Channels in matrix should equal channels number of channel names"
            assert data.shape[1] <= 5, "There should be atmost five frequency bands"
            # reshape to a 3-d matrix with 1 epochs dimension
            data = data.reshape(-1,*data.shape)

        n_epochs : int = data.shape[0]

        self.permutations : torch.Tensor | None = None
        perms_file : str = \
            f"{hamming_selection}_hamming_set_{n_regions}_{n_permutations}.pt"
        perms_path : Path = Path(__file__).resolve().parent.parent.parent / "data"
        if not(os.path.exists(perms_path / perms_file)):
            #print("Permutations not found in path. Running. It may take a minute.")
            self.permutations : torch.Tensor = hamming_set(n_regions=n_regions,
                                                    n_permutations=n_permutations, 
                                                    selection=hamming_selection,
                                                    output_file_name= perms_file, 
                                                    save_to_disk=False)
            torch.save(torch.Tensor(self.permutations), perms_path / perms_file)
        else:
            #print("Loading permutations from disk..")
            self.permutations = torch.load(perms_path / perms_file) 

        regions : dict[int,list[str]] = {
            0 :["Fp1", "Fp2"],
            1 :["Fz", "FCz"],
            2 : ["F7", "F3", "FC3"],
            3 : ["F4", "F8", "FC4"],
            4 : ["T7", "C3", "CP3"],
            5 : ["C4" , "T8", "CP4"],
            6 : ["Cz", "CPz", "Pz"],
            7 : ["P7", "P3"],
            8 : ["P4", "P8"],
            9 : ["O1","Oz", "O2"]
        }

        pseudo_labels = np.random.randint(low = 1,
                                            high = 128,
                                            size = n_epochs)
        target_permutaions : torch.Tensor = self.permutations[pseudo_labels,:]
        shuffled_channels : list[list[int]] = []
        shuffled_data = torch.zeros(data.shape).double()

        for epoch_num, epoch_permutation in enumerate(target_permutaions): 
            shuffled_channels : list[int] = []
            for region in epoch_permutation: # permuted region for that epoch
                for ch in regions[region.item()]:
                    try:
                        ch_index = ch_names.index(ch)
                        shuffled_channels.append(ch_index)
                    except ValueError:
                        # Some channels might be missing due to bad channels 
                        # and user picks.
                        continue
            shuffled_data[epoch_num,:,:] = data[epoch_num,shuffled_channels,:]
        
        assert shuffled_data.shape == data.shape

        if self.save_freq_perms_to_disk:
            self.perm_save_dir : Path = self.project_root /\
                'data' / 'energy' / 'spatial_perms'
            self.perm_save_dir.mkdir(parents=True, exist_ok=True)
            assert os.path.exists(self.perm_save_dir),\
                "Permutation save directory path invalid"
            
            save_path = self.perm_save_dir / f"energy_perms_{file_name}"
            torch.save((shuffled_data, pseudo_labels, file_name), save_path)
            assert os.path.exists(save_path),\
                f"Data file does not exist: {save_path}"
            
        return (shuffled_data.float(), pseudo_labels, file_name)
    
    def run_spatial_permutations_parallel(self, save_to_disk : bool = False):
        """Parallel process the energy objects to generate spatial permutations.

        Args:
        ----
            None 

        Returns:
        -------
            list[tuple[
                        torch.Tensor : Shuffled energy object,
                        int          : a integer pseudolabel for the shuffling applied.
                        ]
                ] 

        """
        if save_to_disk:
            self.save_spatial_perms_to_disk = True
        energy_files : list[str] = os.listdir(self.energy_save_dir)
        energy_files.extend(os.listdir(self.energy_save_dir_epoched))

        #starmap_args : list[tuple[]]]
        max_processes = multiprocessing.cpu_count() -1
        processes = len(energy_files) if len(energy_files) < max_processes \
                                                                else max_processes
        
        print(f'Using {processes} processes for spatial permutation computation')
        print(f"Processing {len(energy_files)} files...")

        with multiprocessing.Pool(processes, initializer=worker_init_fn,
                                    initargs=(os.getpid(),)) \
            as p:
            results = list(tqdm(p.map(self.get_spatial_permutation,
                                            energy_files),
                                total=len(energy_files),
                                desc="Computing spatial band permutations"))

        print(f"Finished processing {len(results)} permutations.")
        assert len(results) == len(energy_files),\
            "Expected numer of permutations results not generated."
        return results
        

if __name__ == "__main__":
    # Set seed for reproducibility or testing different runs
    Config.RANDOM_SEED = 33
    Config.set_global_seed()
    
    cleaned_path = Path(__file__).resolve().parent.parent.parent / 'data' / 'cleaned'
    labels_file = Path(__file__).resolve().parent.parent.parent / 'data' / \
        'TDBRAIN_participants_V2.xlsx'
    dataset = Energy(cleaned_path=cleaned_path,
                     full_time_series=False,
                          energy_plots=True,
                          verbose_psd=False,
                          picks_psd = ['eeg'],
                          include_bad_channels_psd=True,
                          save_to_disk=True,
                          select_freq_bands=['alpha', 'delta','theta'])
    # for f in dataset.folders_and_files:
    #     #print(f"f {f}")
    #     out = dataset.get_energy(*f)
    #     print(out[0].shape)
    dataset.run_energy_parallel()
    dataset.run_freq_permutations_parallel(save_to_disk=True)
    dataset.run_spatial_permutations_parallel(save_to_disk=True)

