import pytest
import numpy as np
import pandas as pd
from pathlib import Path
from eeglearn.preprocess.preprocessing import Preproccesing
import os
import uuid
from eeglearn.config import Config

# Set global seed for all tests
@pytest.fixture(scope="session", autouse=True)
def setup_seed():
    Config.set_global_seed()
    return Config.RANDOM_SEED

@pytest.fixture
def sample_eeg_data():
    """THIS FUNCTION WAS GENERATED BY AI.
    INSPECTEED AND VERIFIED BY AUTHOR."""
    # Check if environment variable is set
    env_file_path = os.environ.get('EEG_TEST_FILE_PATH')
 
    if env_file_path and os.path.exists(env_file_path):
        # Use the file path from the environment variable
        print(f"Using test EEG file from environment: {env_file_path}")
        return str(env_file_path)
    else:
        #skip
        pytest.skip("No environment variable found. Skipping test.")

def test_preprocessing_initialization(sample_eeg_data):
    """THIS FUNCTION WAS GENERATED BY AI.
    INSPECTEED AND VERIFIED BY AUTHOR."""
    # Test with default parameters
    preprocess = Preproccesing(
        filename=sample_eeg_data,
        epochs_length=0,
        line_noise=[],
        sfreq=500,
        plots=False
    )
    
    # Check if basic attributes are created
    assert hasattr(preprocess, 'prep_data'), \
    "prep_data attribute not created"
    assert hasattr(preprocess, 'preprocessed_raw'),\
          "preprocessed_raw attribute not created"
    assert hasattr(preprocess, 'preprocessed_epochs'), \
        "preprocessed_epochs attribute not created"

def test_bad_channel_detection(sample_eeg_data):
    """Test if bad channel detection works.
    
    THIS FUNCTION WAS GENERATED BY AI.
    INSPECTEED AND VERIFIED BY AUTHOR."""
    pass
    #TODO : need to mock with some bad channels and test it.

def test_epoching(sample_eeg_data):
    """Test if epoching works correctly.
    
    THIS FUNCTION WAS GENERATED BY AI.
    INSPECTEED AND VERIFIED BY AUTHOR.
    """
    epoch_length = 2.0  # 2 seconds
    
    preprocess = Preproccesing(
        filename=sample_eeg_data,
        epochs_length=epoch_length,
        line_noise=[],
        sfreq=500,
        plots=False
    )
    
    # Check if epochs were created
    assert preprocess.preprocessed_epochs != 'No epoching applied'
    
    # Check epoch properties
    expected_epoch_samples = int(epoch_length * 500)  # sfreq = 500
    assert preprocess.preprocessed_epochs.get_data().shape[2] == expected_epoch_samples

def test_line_noise_removal(sample_eeg_data):
    "TODO"
    pass

# Error handling tests
def test_invalid_file_handling():
    """Test if the class handles invalid files appropriately.
    
    THIS FUNCTION WAS GENERATED BY AI.
    INSPECTEED AND VERIFIED BY AUTHOR.
    """
    with pytest.raises(FileNotFoundError):
        Preproccesing(
            filename="nonexistent_file.csv",
            epochs_length=0,
            line_noise=[],
            sfreq=500,
            plots=False
        )
