"""Hyperparameter optimization for EEG vanilla training using Optuna.

This module provides automated hyperparameter tuning for the vanilla model for EEG data. 
It uses Optuna's trial-based optimization to find optimal hyperparameters that maximize 
validation performance.

The script optimizes the following hyperparameters:
    - batch_size: Training batch size [128, 256]
    - lr: Learning rate (log-uniform distribution: 1e-4 to 5e-2)
    - weight_decay: L2 regularization strength (log-uniform: 1e-6 to 1e-3)
    - drop_rate: Dropout rate (uniform: 0.1 to 0.4)
    - K: Order of Chebyshev polynomials for graph convolution [1, 2, 3, 4]
    - gcn_out_size: GCN output size [16, 32, 64, 128]
    - linear_size: Linear layer size [256, 512, 1024]

Usage:
    Run the script directly to start hyperparameter optimization:
    ```
    python optuna_tuning_vanilla.py
    ```
    
    Results are saved to 'optuna_results_[timestamp]_[pid].csv'

Author: Udesh Habaraduwa
Created: 2025

WRITTEN WITH AI
REVIEWED AND VERIFIED BY AUTHOR
"""

import optuna, importlib
import torch
import os
from pathlib import Path
from eeglearn.config import Config
from datetime import datetime

Config.set_global_seed(verbose=False)
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
pid = os.getpid()

def objective(trial):
    """Objective function for Optuna hyperparameter optimization.
    
    Args:
        trial (optuna.Trial): Optuna trial object for sampling hyperparameters
        
    Returns:
        float: Validation performance metric to maximize

    THIS FUNCTION WAS GENERATED BY AI.
    INSPECTED AND VERIFIED BY AUTHOR.
    """
    Config.experiment_name = f"optuna_tuur_data_vanilla_{timestamp}_pid{pid}"
    Config.optuna = True
    Config.load_data_split_from = "turr_all_data_train_test_valid_split.pt"

    Config.RANDOM_SEED = 42
    Config.DETERMINISTIC = True

    Config.epochs = 15  
    Config.stop_at = 5

    Config.use_class_weighting = False
    Config.p_train = 0.8
    Config.sample_proportion_of_data = 1.0
    Config.use_tuur_smolder_data = True
    Config.drop_last = True
    Config.skip_bads = True
    Config.main_classes = ["ADHD", "HEALTHY", "MDD", "OCD", "SMC"]
    Config.use_stratify = True
    Config.testing_on_sample_data = False
    
    Config.gcn_out_size = trial.suggest_categorical("gcn_out_size", [16, 32, 64, 128])
    Config.linear_size = trial.suggest_categorical("linear_size", [256, 512, 1024])
    Config.K = trial.suggest_int("K", 1, 4)
    Config.drop_rate = trial.suggest_float("drop_rate", 0.1, 0.4)
    
    Config.lr = trial.suggest_float("lr", 1e-4, 5e-2, log=True)   
    Config.weight_decay = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
    Config.batch_size = trial.suggest_categorical("batch_size", [128, 256])
    
    trainer = importlib.import_module("eeglearn.models.train_vanilla")
    val_metric = trainer.train()   
    return val_metric


if __name__ == "__main__":
    results_filename = f"optuna_results_{timestamp}_pid{pid}.csv"
    pruner = optuna.pruners.MedianPruner(n_warmup_steps=3)
    
    study = optuna.create_study(direction="maximize", pruner=pruner)
    study.optimize(objective, n_trials=30, timeout=60*60*24)   

    print("Best trial:", study.best_trial.params)
    print(f"Best value: {study.best_trial.value:.4f}")
    
    wanted = (
    'number', 'state', 'values',
    'params', 'user_attrs',
    'intermediate_values', 'duration',
    'datetime_start', 'datetime_complete'
    )

    df = study.trials_dataframe(attrs=wanted, multi_index=True)
    df.to_csv(results_filename, index=False)
    print(f"Results saved to '{results_filename}'") 
