"""Hyperparameter optimization for EEG joint training using Optuna - MINIMAL TEST RUN.

This module provides automated hyperparameter tuning for the joint self-supervised 
and multi-task learning model for EEG data. It uses Optuna's trial-based optimization
to find optimal hyperparameters that maximize validation performance.

This version is configured for a minimal test run.

The script optimizes the following hyperparameters:
    - batch_size: Training batch size [128]
    - lr: Learning rate (fixed at 1e-4)
    - weight_decay: L2 regularization strength (fixed at 1e-6)
    - drop_rate: Dropout rate (fixed at 0.1)
    - K: Order of Chebyshev polynomials for graph convolution [1]
    - gcn_out_size: GCN output size [16]
    - linear_size: Linear layer size [256]

Usage:
    Run the script directly to start hyperparameter optimization:
    ```
    python test_optuna_tuning.py
    ```
    
    Results are saved to 'test_optuna_results.csv' containing all trial information.

Requirements:
    - The joint training module (train_jointly.py) must be available
    - Training data and necessary directory structure must be set up
    - Global Config must be properly configured

Author: Udesh Habaraduwa
Created: 2025

WRITTEN WITH AI
REVIEWED AND VERIFIED BY AUTHOR
"""

# optuna_runner.py
import optuna, importlib
import torch
import os
from pathlib import Path
from eeglearn.config import Config

# Make sure torch / cudnn behaves the same
Config.set_global_seed(verbose=False)

def objective(trial):
    """Objective function for Optuna hyperparameter optimization - MINIMAL TEST RUN.
    
    This function defines the hyperparameter search space and trains the model
    with sampled hyperparameters to evaluate their performance.
    
    Args:
        trial (optuna.Trial): Optuna trial object for sampling hyperparameters
        
    Returns:
        float: Validation performance metric (accuracy or F1 score) to maximize
        
    Hyperparameters optimized (minimal set for testing):
        - batch_size: Fixed at [128]
        - lr: Fixed at 1e-4
        - weight_decay: Fixed at 1e-6
        - drop_rate: Fixed at 0.1
        - K: Fixed at 1
        - gcn_out_size: Fixed at [16]
        - linear_size: Fixed at [256]

    THIS FUNCTION WAS GENERATED BY AI.
    INSPECTED AND VERIFIED BY AUTHOR.
    """

    # Remove the non-existent method call and unused data_frac parameter
    # TODO: Implement participant subset functionality if needed for multi-fidelity optimization
    
    # Cap epochs for faster hyperparameter search
    Config.epochs = 1  # Minimal epochs for testing

    Config.optuna = True

    # Model architecture parameters - using correct attribute names (minimal fixed values)
    Config.gcn_out_size = trial.suggest_categorical("gcn_out_size", [16])
    Config.linear_size = trial.suggest_categorical("linear_size", [256])
    Config.K = trial.suggest_int("K", 1, 1)
    Config.drop_rate = trial.suggest_float("drop_rate", 0.1, 0.1) # Fixed value
    
    # Training parameters (minimal fixed values)
    Config.batch_size = trial.suggest_categorical("batch_size", [128])
    Config.lr = trial.suggest_float("lr", 1e-4, 1e-4, log=True) # Fixed value
    Config.weight_decay = trial.suggest_float("weight_decay", 1e-6, 1e-6, log=True) # Fixed value
    
    trainer = importlib.import_module("eeglearn.models.train_jointly")
    val_metric = trainer.train()   
    return val_metric


if __name__ == "__main__":
    # Create pruner to terminate unpromising trials early (minimal warmup)
    pruner = optuna.pruners.MedianPruner(n_warmup_steps=1) 
    
    # Create study for maximizing validation performance
    study  = optuna.create_study(direction="maximize", pruner=pruner)
    
    # Run optimization with 1 trial and short timeout for testing
    study.optimize(objective, n_trials=1, timeout=60*5)   # 5 minute budget

    print("Best trial:", study.best_trial.params)
    print(f"Best value: {study.best_trial.value:.4f}")
    
    # Save detailed results
    wanted = (
    'number', 'state', 'values',           # all objectives
    'params', 'user_attrs',
    'intermediate_values', 'duration',
    'datetime_start', 'datetime_complete'
    )

    df = study.trials_dataframe(attrs=wanted, multi_index=True)
    df.to_csv("test_optuna_results.csv", index=False)
    print("Results saved to 'test_optuna_results.csv'") 