name: eeg-graph-learning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=23.3.1
  - setuptools=68.2.2
  - numpy=1.26.3
  - scipy=1.12.0
  - matplotlib=3.8.2
  - pandas=2.2.3
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - jupyter=1.0.0
  - scikit-learn=1.6.1  # Updated from 1.4.0 to latest stable
  - mne=1.9.0  # Updated from 1.6.1 to latest stable
  - pip:
    - torch_geometric==2.6.1
    - tensorboard==2.15.1
    - pytest==7.4.4
    - optuna==3.5.0
    - pyprep==0.4.3
